name: Deploy to VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Add Go to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: go mod download

      - name: Build app
        run: go build -o pocketbase-new

      - name: Copy app to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r -o StrictHostKeyChecking=no pocketbase-new root@${{ secrets.SSH_IP }}:/root/komublock/back

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            systemctl stop pocketbase.service
            rm /root/komublock/back/pocketbase
            mv /root/komublock/back/pocketbase-new /root/komublock/back/pocketbase
            rm /root/komublock/back/pocketbase-new
            ulimit -n 4096
            systemctl start pocketbase.service
