name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build app
        run: go build -o pocketbase-new

      - name: Copy app to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r -o StrictHostKeyChecking=no pocketbase-new root@${{ secrets.SSH_IP }}:/root/pocketbase

      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            systemctl stop pocketbase.service
            rm /root/pocketbase/pocketbase
            mv /root/pocketbase/pocketbase-new /root/pocketbase/pocketbase
            rm /root/pocketbase/pocketbase-new
            systemctl start pocketbase.service